//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Parts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PartsEntities : DbContext
    {
        public PartsEntities()
            : base("name=PartsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAccessoryList> tblAccessoryLists { get; set; }
        public virtual DbSet<tblAccessoryListPosition> tblAccessoryListPositions { get; set; }
        public virtual DbSet<tblAccessoryPlacement> tblAccessoryPlacements { get; set; }
        public virtual DbSet<tblAccessoryPlacementPosition> tblAccessoryPlacementPositions { get; set; }
        public virtual DbSet<tblAccessoryPosition> tblAccessoryPositions { get; set; }
        public virtual DbSet<tblAssembly> tblAssemblies { get; set; }
        public virtual DbSet<tblBlockingSurfacePosition> tblBlockingSurfacePositions { get; set; }
        public virtual DbSet<tblConstruction> tblConstructions { get; set; }
        public virtual DbSet<tblDoorPosition> tblDoorPositions { get; set; }
        public virtual DbSet<tblDrillingPosition> tblDrillingPositions { get; set; }
        public virtual DbSet<tblFreeProperty> tblFreeProperties { get; set; }
        public virtual DbSet<tblFunctionTemplate> tblFunctionTemplates { get; set; }
        public virtual DbSet<tblMechanic> tblMechanics { get; set; }
        public virtual DbSet<tblModule> tblModules { get; set; }
        public virtual DbSet<tblMountingPanelPosition> tblMountingPanelPositions { get; set; }
        public virtual DbSet<tblOption> tblOptions { get; set; }
        public virtual DbSet<tblPart> Parts { get; set; }
        public virtual DbSet<tblPartConstructionPosition> tblPartConstructionPositions { get; set; }
        public virtual DbSet<tblSafetyRelatedValuePosition> tblSafetyRelatedValuePositions { get; set; }
        public virtual DbSet<tblSupportBarPosition> tblSupportBarPositions { get; set; }
        public virtual DbSet<tblTerminal> tblTerminals { get; set; }
        public virtual DbSet<tblTerminalPosition> tblTerminalPositions { get; set; }
        public virtual DbSet<tblVariant> tblVariants { get; set; }
        public virtual DbSet<tblAddress> tblAddresses { get; set; }
        public virtual DbSet<tblAttribute> tblAttributes { get; set; }
    }
}
