//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Parts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccessoryPlacementPosition
    {
        public int id { get; set; }
        public short pos { get; set; }
        public string name { get; set; }
        public Nullable<short> referencepoint { get; set; }
        public Nullable<double> rotation { get; set; }
        public Nullable<double> xspacing { get; set; }
        public Nullable<double> yspacing { get; set; }
        public Nullable<double> zspacing { get; set; }
        public bool movable { get; set; }
        public int C_uniqueid { get; set; }
    }
}
