//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Parts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssembly
    {
        public Nullable<short> count { get; set; }
        public int id { get; set; }
        public string parentvariant { get; set; }
        public string partnr { get; set; }
        public short pos { get; set; }
        public string additionaltext { get; set; }
        public string posnr { get; set; }
        public string variant { get; set; }
        public int C_uniqueid { get; set; }
    }
}
