//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Parts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddress
    {
        public Nullable<short> @class { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public int id { get; set; }
        public string lastchange { get; set; }
        public string longname { get; set; }
        public string name1 { get; set; }
        public string name2 { get; set; }
        public string name3 { get; set; }
        public string note { get; set; }
        public string number { get; set; }
        public string phone { get; set; }
        public string pobox { get; set; }
        public string shortname { get; set; }
        public string state { get; set; }
        public string street { get; set; }
        public string title { get; set; }
        public string town { get; set; }
        public string zippobox { get; set; }
        public string ziptown { get; set; }
    }
}
