//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Parts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBlockingSurfacePosition
    {
        public bool frontside { get; set; }
        public Nullable<double> height { get; set; }
        public int id { get; set; }
        public short pos { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> xpos { get; set; }
        public Nullable<double> ypos { get; set; }
    }
}
