//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Parts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoorPosition
    {
        public int id { get; set; }
        public string partnr { get; set; }
        public short pos { get; set; }
        public string variant { get; set; }
        public Nullable<double> xpos { get; set; }
        public Nullable<double> ypos { get; set; }
        public Nullable<double> zpos { get; set; }
    }
}
