//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Parts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDrillingPosition
    {
        public Nullable<double> angle { get; set; }
        public Nullable<double> dimension1 { get; set; }
        public Nullable<double> dimension2 { get; set; }
        public Nullable<double> dimension3 { get; set; }
        public Nullable<int> drillnthhole { get; set; }
        public bool fabricatealways { get; set; }
        public int id { get; set; }
        public string outlinename { get; set; }
        public short pos { get; set; }
        public Nullable<double> spacingend { get; set; }
        public Nullable<double> spacingrepeat { get; set; }
        public Nullable<int> subtype { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<double> xpos { get; set; }
        public Nullable<double> ypos { get; set; }
    }
}
