//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Parts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFunctionTemplate
    {
        public string additionaldescription { get; set; }
        public string characteristics { get; set; }
        public string connectioncrosssection { get; set; }
        public string connectionDesignation { get; set; }
        public string connectiondescription { get; set; }
        public string description { get; set; }
        public Nullable<short> functiondefcategory { get; set; }
        public Nullable<short> functiondefgroup { get; set; }
        public Nullable<short> functiondefid { get; set; }
        public bool hasled { get; set; }
        public bool hasplugadapter { get; set; }
        public Nullable<short> hpdlink { get; set; }
        public int id { get; set; }
        public string idx1 { get; set; }
        public string idx2 { get; set; }
        public bool intrinsicsafety { get; set; }
        public string nesteddevicetag { get; set; }
        public string pipeclass { get; set; }
        public Nullable<short> plcbussystem { get; set; }
        public short pos { get; set; }
        public bool safetyrelevant { get; set; }
        public string symbol { get; set; }
        public string symbolmacro { get; set; }
        public Nullable<short> terminalfunction { get; set; }
        public string terminallabeltype { get; set; }
        public string terminalNr { get; set; }
        public string variant { get; set; }
    }
}
