//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Parts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFreeProperty
    {
        public string description { get; set; }
        public int id { get; set; }
        public short pos { get; set; }
        public string unit { get; set; }
        public string val { get; set; }
        public int C_uniqueid { get; set; }
    }
}
