//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Parts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMechanic
    {
        public Nullable<short> barcount { get; set; }
        public Nullable<double> bardistance { get; set; }
        public string bargeometry { get; set; }
        public Nullable<double> barmountingplatedistance { get; set; }
        public Nullable<double> bottompaneldepth { get; set; }
        public Nullable<double> bottompaneldistance { get; set; }
        public Nullable<double> bottompanelprojectionback { get; set; }
        public Nullable<double> bottompanelprojectionfront { get; set; }
        public Nullable<double> bottompanelprojectionleft { get; set; }
        public Nullable<double> bottompanelprojectionright { get; set; }
        public string busbarholderpartnr { get; set; }
        public string busbarholdervariant { get; set; }
        public string busbarrailpartnr { get; set; }
        public string busbarrailvariant { get; set; }
        public Nullable<double> bundlemindiameter { get; set; }
        public Nullable<double> bundlemaxdiameter { get; set; }
        public string conductibility { get; set; }
        public Nullable<double> deliverylength { get; set; }
        public Nullable<double> dooroffsetright { get; set; }
        public Nullable<double> dooroffsettop { get; set; }
        public Nullable<double> doorthickness { get; set; }
        public Nullable<double> doortrabbet { get; set; }
        public string doortype { get; set; }
        public Nullable<int> hingeposition { get; set; }
        public int id { get; set; }
        public Nullable<double> insertpointoffsetx { get; set; }
        public Nullable<double> profiledepth { get; set; }
        public Nullable<double> profiledistance { get; set; }
        public Nullable<double> profileheight { get; set; }
        public Nullable<double> railcrosssection { get; set; }
        public Nullable<short> railmaterial { get; set; }
        public Nullable<double> rearpaneldistance { get; set; }
        public Nullable<double> rearpaneldpepth { get; set; }
        public Nullable<double> rearpanelprojectionbottom { get; set; }
        public Nullable<double> rearpanelprojectionleft { get; set; }
        public Nullable<double> rearpanelprojectionright { get; set; }
        public Nullable<double> rearpanelprojectiontop { get; set; }
        public Nullable<double> sidepaneldepth { get; set; }
        public Nullable<double> sidepaneldistance { get; set; }
        public Nullable<double> sidepanelprojectionback { get; set; }
        public Nullable<double> sidepanelprojectionbottom { get; set; }
        public Nullable<double> sidepanelprojectionfront { get; set; }
        public Nullable<double> sidepanelprojectiontop { get; set; }
        public string temperaturecoefficient { get; set; }
        public Nullable<double> toppaneldistance { get; set; }
        public Nullable<double> toppaneldpepth { get; set; }
        public Nullable<double> toppanelprojectionback { get; set; }
        public Nullable<double> toppanelprojectionfront { get; set; }
        public Nullable<double> toppanelprojectionleft { get; set; }
        public Nullable<double> toppanelprojectionright { get; set; }
        public Nullable<double> vprofiledepth { get; set; }
        public Nullable<double> vprofilewidth { get; set; }
        public Nullable<double> wallthickness { get; set; }
        public Nullable<double> widthbottom { get; set; }
        public Nullable<double> widthtop { get; set; }
    }
}
