//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Parts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPart
    {
        public string accessoriesidentifier { get; set; }
        public bool canbelinedup { get; set; }
        public string certificate { get; set; }
        public string certificate_ATEX { get; set; }
        public bool certificate_CE { get; set; }
        public string certificate_UL { get; set; }
        public string certificate_VDE { get; set; }
        public Nullable<short> @class { get; set; }
        public string codeletter { get; set; }
        public string construction { get; set; }
        public bool craftcooling { get; set; }
        public bool craftelectro { get; set; }
        public bool craftfluid { get; set; }
        public bool crafthydraulic { get; set; }
        public bool craftlubrication { get; set; }
        public bool craftmechanic { get; set; }
        public bool craftpneumatic { get; set; }
        public bool craftprocess { get; set; }
        public bool craftcoolinglubricant { get; set; }
        public bool craftgastechnology { get; set; }
        public bool craftfluidundefined { get; set; }
        public string create { get; set; }
        public Nullable<double> depth { get; set; }
        public Nullable<double> depthspacingfront { get; set; }
        public Nullable<double> depthspacingrear { get; set; }
        public string description1 { get; set; }
        public string description2 { get; set; }
        public string description3 { get; set; }
        public Nullable<double> discount { get; set; }
        public bool discontinued { get; set; }
        public string edpchecksum { get; set; }
        public string ecabinetmacro { get; set; }
        public string erpnr { get; set; }
        public string externalDocument1 { get; set; }
        public string externalDocument2 { get; set; }
        public string externalDocument3 { get; set; }
        public bool externalplacement { get; set; }
        public string functiongroup { get; set; }
        public string graphicmacro { get; set; }
        public string groupnumber { get; set; }
        public string groupsymbolmacro { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> heightspacingabove { get; set; }
        public Nullable<double> heightspacingbelow { get; set; }
        public int id { get; set; }
        public string identcode { get; set; }
        public string identtype { get; set; }
        public Nullable<double> installationdepth { get; set; }
        public bool isaccessory { get; set; }
        public string lastchange { get; set; }
        public string lifetime { get; set; }
        public string macro3d { get; set; }
        public string maintenance { get; set; }
        public string manufacturer { get; set; }
        public Nullable<double> snapheightmiddleoffset { get; set; }
        public Nullable<int> mountinglocation { get; set; }
        public Nullable<double> mountingspace { get; set; }
        public string note { get; set; }
        public string ordernr { get; set; }
        public Nullable<decimal> packagingprice1 { get; set; }
        public Nullable<decimal> packagingprice2 { get; set; }
        public Nullable<double> packagingquantity { get; set; }
        public string partnr { get; set; }
        public string picturefile { get; set; }
        public string piecetype { get; set; }
        public Nullable<short> priceunit { get; set; }
        public Nullable<short> productgroup { get; set; }
        public Nullable<short> productsubgroup { get; set; }
        public Nullable<short> producttopgroup { get; set; }
        public Nullable<decimal> purchaseprice1 { get; set; }
        public Nullable<decimal> purchaseprice2 { get; set; }
        public string quantityunit { get; set; }
        public string reportid { get; set; }
        public Nullable<decimal> salesprice1 { get; set; }
        public Nullable<decimal> salesprice2 { get; set; }
        public Nullable<double> snapheight { get; set; }
        public string spare { get; set; }
        public string stress { get; set; }
        public string supplier { get; set; }
        public string terminal { get; set; }
        public Nullable<double> terminaloffsetx { get; set; }
        public Nullable<double> terminaloffsety { get; set; }
        public string typenr { get; set; }
        public string uniqueid { get; set; }
        public string usage { get; set; }
        public string wear { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> widthspacingleft { get; set; }
        public Nullable<double> widthspacingright { get; set; }
    }
}
