//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Parts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartConstructionPosition
    {
        public int id { get; set; }
        public short pos { get; set; }
        public string name { get; set; }
        public Nullable<double> offsetx { get; set; }
        public Nullable<double> offsety { get; set; }
    }
}
