//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Parts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSafetyRelatedValuePosition
    {
        public int id { get; set; }
        public short pos { get; set; }
        public short posid { get; set; }
        public string hierarchy1 { get; set; }
        public string hierarchy2 { get; set; }
        public string hierarchy3 { get; set; }
        public string hierarchy4 { get; set; }
        public string hierarchy5 { get; set; }
        public bool input { get; set; }
        public bool output { get; set; }
        public bool logic { get; set; }
        public string pl { get; set; }
        public string silcl { get; set; }
        public Nullable<double> pfhd { get; set; }
        public Nullable<double> tmt1 { get; set; }
        public Nullable<double> mttfd { get; set; }
        public Nullable<double> lambdad { get; set; }
        public Nullable<double> mttf { get; set; }
        public Nullable<double> mtbf { get; set; }
        public Nullable<double> rdf { get; set; }
        public Nullable<double> b10 { get; set; }
        public Nullable<double> b10d { get; set; }
    }
}
