//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Parts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTerminalPosition
    {
        public Nullable<double> additionallength { get; set; }
        public string devicetag { get; set; }
        public Nullable<int> direction { get; set; }
        public int id { get; set; }
        public Nullable<short> level { get; set; }
        public Nullable<double> maxcrosssection { get; set; }
        public Nullable<int> maxwirecount { get; set; }
        public Nullable<double> mincrosssection { get; set; }
        public string name { get; set; }
        public short pos { get; set; }
        public Nullable<short> targetinfo { get; set; }
        public string terminalsize { get; set; }
        public bool twinsleeve { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> typeofterminal { get; set; }
        public Nullable<double> xpos { get; set; }
        public Nullable<double> ypos { get; set; }
        public Nullable<double> zpos { get; set; }
        public Nullable<double> xdir { get; set; }
        public Nullable<double> ydir { get; set; }
        public Nullable<double> zdir { get; set; }
    }
}
