//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Parts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTerminal
    {
        public Nullable<double> additionallengthdefault { get; set; }
        public Nullable<short> @class { get; set; }
        public string create { get; set; }
        public string designation { get; set; }
        public Nullable<int> direction { get; set; }
        public int id { get; set; }
        public string lastchange { get; set; }
        public string name { get; set; }
        public string terminalsizedefault { get; set; }
        public Nullable<int> typedefault { get; set; }
        public Nullable<int> typeofterminaldefault { get; set; }
    }
}
