//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Parts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVariant
    {
        public Nullable<double> adjustrange { get; set; }
        public string adressrange { get; set; }
        public string adressrange2 { get; set; }
        public string advancecontacts { get; set; }
        public string airgap { get; set; }
        public bool assemblyspreaded { get; set; }
        public string awgfrom { get; set; }
        public string awgtill { get; set; }
        public string bendingradius { get; set; }
        public string cabledesignation { get; set; }
        public string cabledisplayform { get; set; }
        public Nullable<double> cablelength { get; set; }
        public string cabletype { get; set; }
        public string cableweight { get; set; }
        public string coding { get; set; }
        public string color { get; set; }
        public string connection { get; set; }
        public string connectioncrosssection { get; set; }
        public string connectiondesignation { get; set; }
        public string connectionmethod { get; set; }
        public string contactarrangement { get; set; }
        public string contacttype { get; set; }
        public string coppernumber { get; set; }
        public string creepagedistance { get; set; }
        public string crosssectionfrom { get; set; }
        public string crosssectiontill { get; set; }
        public string currentCSA { get; set; }
        public string currentIEC { get; set; }
        public string currentUL { get; set; }
        public string degofprotection { get; set; }
        public string design { get; set; }
        public Nullable<double> doordepth { get; set; }
        public Nullable<double> doorheight { get; set; }
        public Nullable<double> doormountingspace { get; set; }
        public Nullable<double> doorwidth { get; set; }
        public string electricalcurrent { get; set; }
        public string electricalpower { get; set; }
        public string firmwareversion { get; set; }
        public Nullable<double> flow { get; set; }
        public string fluidwallthickness { get; set; }
        public string holdingpower { get; set; }
        public int id { get; set; }
        public string innerdiameter { get; set; }
        public bool intrinsicsafety { get; set; }
        public string material { get; set; }
        public string norm { get; set; }
        public string outerdiameter { get; set; }
        public Nullable<double> paneldepth { get; set; }
        public Nullable<double> panelheight { get; set; }
        public Nullable<double> panelmountingspace { get; set; }
        public Nullable<double> panelwidth { get; set; }
        public string pincount { get; set; }
        public string pipeclass { get; set; }
        public string plcdeviceid { get; set; }
        public bool plcisbuscoupler { get; set; }
        public bool plcisbusdistributor { get; set; }
        public bool plciscpu { get; set; }
        public bool plcispowersupply { get; set; }
        public string plcobjectdescription { get; set; }
        public string plcstationtype { get; set; }
        public string plctype { get; set; }
        public string powerdissipation { get; set; }
        public Nullable<double> pressure { get; set; }
        public string pressurelevel { get; set; }
        public bool shortcircuitresistant { get; set; }
        public string standardinvers { get; set; }
        public string strokelength { get; set; }
        public string symbolfile { get; set; }
        public string symbolnr { get; set; }
        public string technicalcharacteristics { get; set; }
        public string thread { get; set; }
        public string triggercurrent { get; set; }
        public string variant { get; set; }
        public string voltage { get; set; }
        public string voltageCSA { get; set; }
        public string voltageIEC { get; set; }
        public string voltageUL { get; set; }
        public string voltagetype { get; set; }
        public string widthrating { get; set; }
        public string wirecount { get; set; }
        public string wirecrosssection { get; set; }
        public string wirecrosssectionanddiameter { get; set; }
        public Nullable<short> wirecrosssectionunit { get; set; }
        public int C_uniqueid { get; set; }
    }
}
