//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Translations
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        public string Comment { get; set; }
        public int C_uniqueid { get; set; }
        public string de_DE_Match { get; set; }
        public string de_DE_Entry { get; set; }
        public string en_US_Match { get; set; }
        public string en_US_Entry { get; set; }
    }
}
