//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.Translations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TranslationEntities : DbContext
    {
        public TranslationEntities()
            : base("name=TranslationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NonTranslatedWord> NonTranslatedWords { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<Translation> Translations { get; set; }
        public virtual DbSet<Version> Versions { get; set; }
    }
}
