//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.ProjectManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectEntities : DbContext
    {
        public ProjectEntities()
            : base("name=ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Directory> Directories { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Properties_FLOAT> Properties_FLOAT { get; set; }
        public virtual DbSet<Properties_INT> Properties_INT { get; set; }
        public virtual DbSet<Properties_STR> Properties_STR { get; set; }
        public virtual DbSet<Version> Versions { get; set; }
    }
}
