//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Properties_STR
    {
        public int Project_ID { get; set; }
        public int Property_ID { get; set; }
        public int Property_Index { get; set; }
        public string Property_STR_Value { get; set; }
        public string UserProp_Ident { get; set; }
        public string UserProp_Name { get; set; }
        public Nullable<int> UserProp_Category { get; set; }
        public Nullable<int> UserProp_Type { get; set; }
        public Nullable<int> UserProp_DisplayType { get; set; }
    }
}
