//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Properties_INT
    {
        public int Project_ID { get; set; }
        public int Property_ID { get; set; }
        public int Property_Index { get; set; }
        public int Property_INT_Value { get; set; }
    }
}
