//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suplanus.Eplan.Database.ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version
    {
        public int Ver_ID { get; set; }
        public int Ver_Min_ID { get; set; }
    }
}
